/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'client' : IDL.Null,
  'freelancer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'hourlyRate' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'client' : IDL.Principal,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'isOpen' : IDL.Bool,
  'category' : IDL.Text,
  'budget' : IDL.Nat,
});
export const ProposalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Proposal = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProposalStatus,
  'coverLetter' : IDL.Text,
  'projectId' : IDL.Nat,
  'proposedPrice' : IDL.Nat,
  'freelancer' : IDL.Principal,
});
export const Rating = IDL.Record({
  'client' : IDL.Principal,
  'comment' : IDL.Text,
  'stars' : IDL.Nat,
  'projectId' : IDL.Nat,
  'freelancer' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRating' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'closeProject' : IDL.Func([IDL.Nat], [], []),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllFreelancers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllOpenProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getClientProjects' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'getFreelancerProposals' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Proposal)],
      ['query'],
    ),
  'getFreelancerRatings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Rating)],
      ['query'],
    ),
  'getProjectProposals' : IDL.Func([IDL.Nat], [IDL.Vec(Proposal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, UserRole],
      [],
      [],
    ),
  'reviewProposal' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitProposal' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'client' : IDL.Null,
    'freelancer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'hourlyRate' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'client' : IDL.Principal,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'isOpen' : IDL.Bool,
    'category' : IDL.Text,
    'budget' : IDL.Nat,
  });
  const ProposalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Proposal = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProposalStatus,
    'coverLetter' : IDL.Text,
    'projectId' : IDL.Nat,
    'proposedPrice' : IDL.Nat,
    'freelancer' : IDL.Principal,
  });
  const Rating = IDL.Record({
    'client' : IDL.Principal,
    'comment' : IDL.Text,
    'stars' : IDL.Nat,
    'projectId' : IDL.Nat,
    'freelancer' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRating' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'closeProject' : IDL.Func([IDL.Nat], [], []),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllFreelancers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllOpenProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getClientProjects' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getFreelancerProposals' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Proposal)],
        ['query'],
      ),
    'getFreelancerRatings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Rating)],
        ['query'],
      ),
    'getProjectProposals' : IDL.Func([IDL.Nat], [IDL.Vec(Proposal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, UserRole],
        [],
        [],
      ),
    'reviewProposal' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitProposal' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };