/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Project {
  'id' : bigint,
  'client' : Principal,
  'title' : string,
  'description' : string,
  'deadline' : string,
  'isOpen' : boolean,
  'category' : string,
  'budget' : bigint,
}
export interface Proposal {
  'id' : bigint,
  'status' : ProposalStatus,
  'coverLetter' : string,
  'projectId' : bigint,
  'proposedPrice' : bigint,
  'freelancer' : Principal,
}
export type ProposalStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface Rating {
  'client' : Principal,
  'comment' : string,
  'stars' : bigint,
  'projectId' : bigint,
  'freelancer' : Principal,
}
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'role' : UserRole,
  'hourlyRate' : bigint,
  'skills' : Array<string>,
}
export type UserRole = { 'client' : null } |
  { 'freelancer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRating' : ActorMethod<[Principal, bigint, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'closeProject' : ActorMethod<[bigint], undefined>,
  'createProject' : ActorMethod<
    [string, string, string, bigint, string],
    bigint
  >,
  'getAllFreelancers' : ActorMethod<[], Array<UserProfile>>,
  'getAllOpenProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getClientProjects' : ActorMethod<[Principal], Array<Project>>,
  'getFreelancerProposals' : ActorMethod<[Principal], Array<Proposal>>,
  'getFreelancerRatings' : ActorMethod<[Principal], Array<Rating>>,
  'getProjectProposals' : ActorMethod<[bigint], Array<Proposal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<
    [string, string, Array<string>, bigint, UserRole],
    undefined
  >,
  'reviewProposal' : ActorMethod<[bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitProposal' : ActorMethod<[bigint, string, bigint], bigint>,
  'updateUserProfile' : ActorMethod<
    [string, string, Array<string>, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];